trigger:
  batch: true
  branches:
    include:
    - master
    
pool:
  vmImage: windows-latest

stages:
- stage: NugetPublish
  displayName: 
  jobs:
    - job: SignFiles
      steps:
        - checkout: self
        - task: PowerShell@1
          displayName: 'Build-PowershelScripts'
          inputs:
              scriptName: 'Modules/Build-AllFCModules.ps1'
        - task: NuGetCommand@2
          displayName: 'NuGet pack'
          inputs:
            command: pack
            packagesToPack: '**\*.nuspec'