pool:
  vmImage: windows-latest
#Your build pipeline references an undefined variable named ‘$env:USERNAME’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: PowerShell@1
  displayName: 'Build-PowershelScripts'
  inputs:
    scriptName: 'Modules/Build-AllFCModules.ps1'

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: '**\*.nuspec'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Powershell Scripts'
  inputs:
    PathtoPublish: 'Powershell Scripts'
    ArtifactName: 'Powershell Scripts'
